"""
Pokemon Species Constants for Pokemon Emerald (US).

Species IDs are from the pokeemerald decompilation project:
https://github.com/pret/pokeemerald/blob/master/include/constants/species.h

These IDs are used in the game's memory structures and are required for
decrypting Pokemon data from RAM.
"""

# =============================================================================
# Special Values
# =============================================================================
SPECIES_NONE = 0
SPECIES_EGG = 412

# =============================================================================
# Generation I (Kanto) - IDs 1-151
# =============================================================================
SPECIES_BULBASAUR = 1
SPECIES_IVYSAUR = 2
SPECIES_VENUSAUR = 3
SPECIES_CHARMANDER = 4
SPECIES_CHARMELEON = 5
SPECIES_CHARIZARD = 6
SPECIES_SQUIRTLE = 7
SPECIES_WARTORTLE = 8
SPECIES_BLASTOISE = 9
SPECIES_CATERPIE = 10
SPECIES_METAPOD = 11
SPECIES_BUTTERFREE = 12
SPECIES_WEEDLE = 13
SPECIES_KAKUNA = 14
SPECIES_BEEDRILL = 15
SPECIES_PIDGEY = 16
SPECIES_PIDGEOTTO = 17
SPECIES_PIDGEOT = 18
SPECIES_RATTATA = 19
SPECIES_RATICATE = 20
SPECIES_SPEAROW = 21
SPECIES_FEAROW = 22
SPECIES_EKANS = 23
SPECIES_ARBOK = 24
SPECIES_PIKACHU = 25
SPECIES_RAICHU = 26
SPECIES_SANDSHREW = 27
SPECIES_SANDSLASH = 28
SPECIES_NIDORAN_F = 29
SPECIES_NIDORINA = 30
SPECIES_NIDOQUEEN = 31
SPECIES_NIDORAN_M = 32
SPECIES_NIDORINO = 33
SPECIES_NIDOKING = 34
SPECIES_CLEFAIRY = 35
SPECIES_CLEFABLE = 36
SPECIES_VULPIX = 37
SPECIES_NINETALES = 38
SPECIES_JIGGLYPUFF = 39
SPECIES_WIGGLYTUFF = 40
SPECIES_ZUBAT = 41
SPECIES_GOLBAT = 42
SPECIES_ODDISH = 43
SPECIES_GLOOM = 44
SPECIES_VILEPLUME = 45
SPECIES_PARAS = 46
SPECIES_PARASECT = 47
SPECIES_VENONAT = 48
SPECIES_VENOMOTH = 49
SPECIES_DIGLETT = 50
SPECIES_DUGTRIO = 51
SPECIES_MEOWTH = 52
SPECIES_PERSIAN = 53
SPECIES_PSYDUCK = 54
SPECIES_GOLDUCK = 55
SPECIES_MANKEY = 56
SPECIES_PRIMEAPE = 57
SPECIES_GROWLITHE = 58
SPECIES_ARCANINE = 59
SPECIES_POLIWAG = 60
SPECIES_POLIWHIRL = 61
SPECIES_POLIWRATH = 62
SPECIES_ABRA = 63
SPECIES_KADABRA = 64
SPECIES_ALAKAZAM = 65
SPECIES_MACHOP = 66
SPECIES_MACHOKE = 67
SPECIES_MACHAMP = 68
SPECIES_BELLSPROUT = 69
SPECIES_WEEPINBELL = 70
SPECIES_VICTREEBEL = 71
SPECIES_TENTACOOL = 72
SPECIES_TENTACRUEL = 73
SPECIES_GEODUDE = 74
SPECIES_GRAVELER = 75
SPECIES_GOLEM = 76
SPECIES_PONYTA = 77
SPECIES_RAPIDASH = 78
SPECIES_SLOWPOKE = 79
SPECIES_SLOWBRO = 80
SPECIES_MAGNEMITE = 81
SPECIES_MAGNETON = 82
SPECIES_FARFETCHD = 83
SPECIES_DODUO = 84
SPECIES_DODRIO = 85
SPECIES_SEEL = 86
SPECIES_DEWGONG = 87
SPECIES_GRIMER = 88
SPECIES_MUK = 89
SPECIES_SHELLDER = 90
SPECIES_CLOYSTER = 91
SPECIES_GASTLY = 92
SPECIES_HAUNTER = 93
SPECIES_GENGAR = 94
SPECIES_ONIX = 95
SPECIES_DROWZEE = 96
SPECIES_HYPNO = 97
SPECIES_KRABBY = 98
SPECIES_KINGLER = 99
SPECIES_VOLTORB = 100
SPECIES_ELECTRODE = 101
SPECIES_EXEGGCUTE = 102
SPECIES_EXEGGUTOR = 103
SPECIES_CUBONE = 104
SPECIES_MAROWAK = 105
SPECIES_HITMONLEE = 106
SPECIES_HITMONCHAN = 107
SPECIES_LICKITUNG = 108
SPECIES_KOFFING = 109
SPECIES_WEEZING = 110
SPECIES_RHYHORN = 111
SPECIES_RHYDON = 112
SPECIES_CHANSEY = 113
SPECIES_TANGELA = 114
SPECIES_KANGASKHAN = 115
SPECIES_HORSEA = 116
SPECIES_SEADRA = 117
SPECIES_GOLDEEN = 118
SPECIES_SEAKING = 119
SPECIES_STARYU = 120
SPECIES_STARMIE = 121
SPECIES_MR_MIME = 122
SPECIES_SCYTHER = 123
SPECIES_JYNX = 124
SPECIES_ELECTABUZZ = 125
SPECIES_MAGMAR = 126
SPECIES_PINSIR = 127
SPECIES_TAUROS = 128
SPECIES_MAGIKARP = 129
SPECIES_GYARADOS = 130
SPECIES_LAPRAS = 131
SPECIES_DITTO = 132
SPECIES_EEVEE = 133
SPECIES_VAPOREON = 134
SPECIES_JOLTEON = 135
SPECIES_FLAREON = 136
SPECIES_PORYGON = 137
SPECIES_OMANYTE = 138
SPECIES_OMASTAR = 139
SPECIES_KABUTO = 140
SPECIES_KABUTOPS = 141
SPECIES_AERODACTYL = 142
SPECIES_SNORLAX = 143
SPECIES_ARTICUNO = 144
SPECIES_ZAPDOS = 145
SPECIES_MOLTRES = 146
SPECIES_DRATINI = 147
SPECIES_DRAGONAIR = 148
SPECIES_DRAGONITE = 149
SPECIES_MEWTWO = 150
SPECIES_MEW = 151

# =============================================================================
# Generation II (Johto) - IDs 152-251
# =============================================================================
SPECIES_CHIKORITA = 152
SPECIES_BAYLEEF = 153
SPECIES_MEGANIUM = 154
SPECIES_CYNDAQUIL = 155
SPECIES_QUILAVA = 156
SPECIES_TYPHLOSION = 157
SPECIES_TOTODILE = 158
SPECIES_CROCONAW = 159
SPECIES_FERALIGATR = 160
SPECIES_SENTRET = 161
SPECIES_FURRET = 162
SPECIES_HOOTHOOT = 163
SPECIES_NOCTOWL = 164
SPECIES_LEDYBA = 165
SPECIES_LEDIAN = 166
SPECIES_SPINARAK = 167
SPECIES_ARIADOS = 168
SPECIES_CROBAT = 169
SPECIES_CHINCHOU = 170
SPECIES_LANTURN = 171
SPECIES_PICHU = 172
SPECIES_CLEFFA = 173
SPECIES_IGGLYBUFF = 174
SPECIES_TOGEPI = 175
SPECIES_TOGETIC = 176
SPECIES_NATU = 177
SPECIES_XATU = 178
SPECIES_MAREEP = 179
SPECIES_FLAAFFY = 180
SPECIES_AMPHAROS = 181
SPECIES_BELLOSSOM = 182
SPECIES_MARILL = 183
SPECIES_AZUMARILL = 184
SPECIES_SUDOWOODO = 185
SPECIES_POLITOED = 186
SPECIES_HOPPIP = 187
SPECIES_SKIPLOOM = 188
SPECIES_JUMPLUFF = 189
SPECIES_AIPOM = 190
SPECIES_SUNKERN = 191
SPECIES_SUNFLORA = 192
SPECIES_YANMA = 193
SPECIES_WOOPER = 194
SPECIES_QUAGSIRE = 195
SPECIES_ESPEON = 196
SPECIES_UMBREON = 197
SPECIES_MURKROW = 198
SPECIES_SLOWKING = 199
SPECIES_MISDREAVUS = 200
SPECIES_UNOWN = 201
SPECIES_WOBBUFFET = 202
SPECIES_GIRAFARIG = 203
SPECIES_PINECO = 204
SPECIES_FORRETRESS = 205
SPECIES_DUNSPARCE = 206
SPECIES_GLIGAR = 207
SPECIES_STEELIX = 208
SPECIES_SNUBBULL = 209
SPECIES_GRANBULL = 210
SPECIES_QWILFISH = 211
SPECIES_SCIZOR = 212
SPECIES_SHUCKLE = 213
SPECIES_HERACROSS = 214
SPECIES_SNEASEL = 215
SPECIES_TEDDIURSA = 216
SPECIES_URSARING = 217
SPECIES_SLUGMA = 218
SPECIES_MAGCARGO = 219
SPECIES_SWINUB = 220
SPECIES_PILOSWINE = 221
SPECIES_CORSOLA = 222
SPECIES_REMORAID = 223
SPECIES_OCTILLERY = 224
SPECIES_DELIBIRD = 225
SPECIES_MANTINE = 226
SPECIES_SKARMORY = 227
SPECIES_HOUNDOUR = 228
SPECIES_HOUNDOOM = 229
SPECIES_KINGDRA = 230
SPECIES_PHANPY = 231
SPECIES_DONPHAN = 232
SPECIES_PORYGON2 = 233
SPECIES_STANTLER = 234
SPECIES_SMEARGLE = 235
SPECIES_TYROGUE = 236
SPECIES_HITMONTOP = 237
SPECIES_SMOOCHUM = 238
SPECIES_ELEKID = 239
SPECIES_MAGBY = 240
SPECIES_MILTANK = 241
SPECIES_BLISSEY = 242
SPECIES_RAIKOU = 243
SPECIES_ENTEI = 244
SPECIES_SUICUNE = 245
SPECIES_LARVITAR = 246
SPECIES_PUPITAR = 247
SPECIES_TYRANITAR = 248
SPECIES_LUGIA = 249
SPECIES_HO_OH = 250
SPECIES_CELEBI = 251

# =============================================================================
# Generation III (Hoenn) - IDs 277-411
# Note: IDs 252-276 are unused in Gen III games
# =============================================================================
SPECIES_TREECKO = 277
SPECIES_GROVYLE = 278
SPECIES_SCEPTILE = 279
SPECIES_TORCHIC = 280
SPECIES_COMBUSKEN = 281
SPECIES_BLAZIKEN = 282
SPECIES_MUDKIP = 283
SPECIES_MARSHTOMP = 284
SPECIES_SWAMPERT = 285
SPECIES_POOCHYENA = 286
SPECIES_MIGHTYENA = 287
SPECIES_ZIGZAGOON = 288
SPECIES_LINOONE = 289
SPECIES_WURMPLE = 290
SPECIES_SILCOON = 291
SPECIES_BEAUTIFLY = 292
SPECIES_CASCOON = 293
SPECIES_DUSTOX = 294
SPECIES_LOTAD = 295
SPECIES_LOMBRE = 296
SPECIES_LUDICOLO = 297
SPECIES_SEEDOT = 298
SPECIES_NUZLEAF = 299
SPECIES_SHIFTRY = 300
SPECIES_NINCADA = 301
SPECIES_NINJASK = 302
SPECIES_SHEDINJA = 303
SPECIES_TAILLOW = 304
SPECIES_SWELLOW = 305
SPECIES_SHROOMISH = 306
SPECIES_BRELOOM = 307
SPECIES_SPINDA = 308
SPECIES_WINGULL = 309
SPECIES_PELIPPER = 310
SPECIES_SURSKIT = 311
SPECIES_MASQUERAIN = 312
SPECIES_WAILMER = 313
SPECIES_WAILORD = 314
SPECIES_SKITTY = 315
SPECIES_DELCATTY = 316
SPECIES_KECLEON = 317
SPECIES_BALTOY = 318
SPECIES_CLAYDOL = 319
SPECIES_NOSEPASS = 320
SPECIES_TORKOAL = 321
SPECIES_SABLEYE = 322
SPECIES_BARBOACH = 323
SPECIES_WHISCASH = 324
SPECIES_LUVDISC = 325
SPECIES_CORPHISH = 326
SPECIES_CRAWDAUNT = 327
SPECIES_FEEBAS = 328
SPECIES_MILOTIC = 329
SPECIES_CARVANHA = 330
SPECIES_SHARPEDO = 331
SPECIES_TRAPINCH = 332
SPECIES_VIBRAVA = 333
SPECIES_FLYGON = 334
SPECIES_MAKUHITA = 335
SPECIES_HARIYAMA = 336
SPECIES_ELECTRIKE = 337
SPECIES_MANECTRIC = 338
SPECIES_NUMEL = 339
SPECIES_CAMERUPT = 340
SPECIES_SPHEAL = 341
SPECIES_SEALEO = 342
SPECIES_WALREIN = 343
SPECIES_CACNEA = 344
SPECIES_CACTURNE = 345
SPECIES_SNORUNT = 346
SPECIES_GLALIE = 347
SPECIES_LUNATONE = 348
SPECIES_SOLROCK = 349
SPECIES_AZURILL = 350
SPECIES_SPOINK = 351
SPECIES_GRUMPIG = 352
SPECIES_PLUSLE = 353
SPECIES_MINUN = 354
SPECIES_MAWILE = 355
SPECIES_MEDITITE = 356
SPECIES_MEDICHAM = 357
SPECIES_SWABLU = 358
SPECIES_ALTARIA = 359
SPECIES_WYNAUT = 360
SPECIES_DUSKULL = 361
SPECIES_DUSCLOPS = 362
SPECIES_ROSELIA = 363
SPECIES_SLAKOTH = 364
SPECIES_VIGOROTH = 365
SPECIES_SLAKING = 366
SPECIES_GULPIN = 367
SPECIES_SWALOT = 368
SPECIES_TROPIUS = 369
SPECIES_WHISMUR = 370
SPECIES_LOUDRED = 371
SPECIES_EXPLOUD = 372
SPECIES_CLAMPERL = 373
SPECIES_HUNTAIL = 374
SPECIES_GOREBYSS = 375
SPECIES_ABSOL = 376
SPECIES_SHUPPET = 377
SPECIES_BANETTE = 378
SPECIES_SEVIPER = 379
SPECIES_ZANGOOSE = 380
SPECIES_RELICANTH = 381
SPECIES_ARON = 382
SPECIES_LAIRON = 383
SPECIES_AGGRON = 384
SPECIES_CASTFORM = 385
SPECIES_VOLBEAT = 386
SPECIES_ILLUMISE = 387
SPECIES_LILEEP = 388
SPECIES_CRADILY = 389
SPECIES_ANORITH = 390
SPECIES_ARMALDO = 391
SPECIES_RALTS = 392
SPECIES_KIRLIA = 393
SPECIES_GARDEVOIR = 394
SPECIES_BAGON = 395
SPECIES_SHELGON = 396
SPECIES_SALAMENCE = 397
SPECIES_BELDUM = 398
SPECIES_METANG = 399
SPECIES_METAGROSS = 400
SPECIES_REGIROCK = 401
SPECIES_REGICE = 402
SPECIES_REGISTEEL = 403
SPECIES_KYOGRE = 404
SPECIES_GROUDON = 405
SPECIES_RAYQUAZA = 406
SPECIES_LATIAS = 407
SPECIES_LATIOS = 408
SPECIES_JIRACHI = 409
SPECIES_DEOXYS = 410
SPECIES_CHIMECHO = 411

# =============================================================================
# Unown Forms - IDs 413-438
# =============================================================================
SPECIES_UNOWN_B = 413
SPECIES_UNOWN_C = 414
SPECIES_UNOWN_D = 415
SPECIES_UNOWN_E = 416
SPECIES_UNOWN_F = 417
SPECIES_UNOWN_G = 418
SPECIES_UNOWN_H = 419
SPECIES_UNOWN_I = 420
SPECIES_UNOWN_J = 421
SPECIES_UNOWN_K = 422
SPECIES_UNOWN_L = 423
SPECIES_UNOWN_M = 424
SPECIES_UNOWN_N = 425
SPECIES_UNOWN_O = 426
SPECIES_UNOWN_P = 427
SPECIES_UNOWN_Q = 428
SPECIES_UNOWN_R = 429
SPECIES_UNOWN_S = 430
SPECIES_UNOWN_T = 431
SPECIES_UNOWN_U = 432
SPECIES_UNOWN_V = 433
SPECIES_UNOWN_W = 434
SPECIES_UNOWN_X = 435
SPECIES_UNOWN_Y = 436
SPECIES_UNOWN_Z = 437
SPECIES_UNOWN_EXCLAMATION = 438  # "!"
SPECIES_UNOWN_QUESTION = 439     # "?"

# =============================================================================
# Lookup Dictionaries
# =============================================================================

# ID to Name mapping (common species used in shiny hunting)
SPECIES_NAMES = {
    # Starters
    SPECIES_TREECKO: "Treecko",
    SPECIES_GROVYLE: "Grovyle",
    SPECIES_SCEPTILE: "Sceptile",
    SPECIES_TORCHIC: "Torchic",
    SPECIES_COMBUSKEN: "Combusken",
    SPECIES_BLAZIKEN: "Blaziken",
    SPECIES_MUDKIP: "Mudkip",
    SPECIES_MARSHTOMP: "Marshtomp",
    SPECIES_SWAMPERT: "Swampert",

    # Route 101
    SPECIES_POOCHYENA: "Poochyena",
    SPECIES_ZIGZAGOON: "Zigzagoon",
    SPECIES_WURMPLE: "Wurmple",

    # Route 102
    SPECIES_LOTAD: "Lotad",
    SPECIES_SEEDOT: "Seedot",
    SPECIES_RALTS: "Ralts",

    # Common wild Pokemon
    SPECIES_TAILLOW: "Taillow",
    SPECIES_WINGULL: "Wingull",
    SPECIES_SHROOMISH: "Shroomish",
    SPECIES_SLAKOTH: "Slakoth",
    SPECIES_ABRA: "Abra",
    SPECIES_SKITTY: "Skitty",
    SPECIES_MAKUHITA: "Makuhita",
    SPECIES_NINCADA: "Nincada",
    SPECIES_WHISMUR: "Whismur",
    SPECIES_ARON: "Aron",
    SPECIES_SABLEYE: "Sableye",
    SPECIES_MAWILE: "Mawile",
    SPECIES_MEDITITE: "Meditite",
    SPECIES_ELECTRIKE: "Electrike",
    SPECIES_PLUSLE: "Plusle",
    SPECIES_MINUN: "Minun",
    SPECIES_VOLBEAT: "Volbeat",
    SPECIES_ILLUMISE: "Illumise",
    SPECIES_GULPIN: "Gulpin",
    SPECIES_NUMEL: "Numel",
    SPECIES_TORKOAL: "Torkoal",
    SPECIES_SPOINK: "Spoink",
    SPECIES_SPINDA: "Spinda",
    SPECIES_TRAPINCH: "Trapinch",
    SPECIES_CACNEA: "Cacnea",
    SPECIES_SWABLU: "Swablu",
    SPECIES_ZANGOOSE: "Zangoose",
    SPECIES_SEVIPER: "Seviper",
    SPECIES_SOLROCK: "Solrock",
    SPECIES_LUNATONE: "Lunatone",
    SPECIES_BARBOACH: "Barboach",
    SPECIES_CORPHISH: "Corphish",
    SPECIES_BALTOY: "Baltoy",
    SPECIES_LILEEP: "Lileep",
    SPECIES_ANORITH: "Anorith",
    SPECIES_FEEBAS: "Feebas",
    SPECIES_CASTFORM: "Castform",
    SPECIES_KECLEON: "Kecleon",
    SPECIES_SHUPPET: "Shuppet",
    SPECIES_DUSKULL: "Duskull",
    SPECIES_TROPIUS: "Tropius",
    SPECIES_CHIMECHO: "Chimecho",
    SPECIES_ABSOL: "Absol",
    SPECIES_SNORUNT: "Snorunt",
    SPECIES_SPHEAL: "Spheal",
    SPECIES_CLAMPERL: "Clamperl",
    SPECIES_RELICANTH: "Relicanth",
    SPECIES_LUVDISC: "Luvdisc",
    SPECIES_BAGON: "Bagon",
    SPECIES_BELDUM: "Beldum",

    # Legendaries
    SPECIES_REGIROCK: "Regirock",
    SPECIES_REGICE: "Regice",
    SPECIES_REGISTEEL: "Registeel",
    SPECIES_LATIAS: "Latias",
    SPECIES_LATIOS: "Latios",
    SPECIES_KYOGRE: "Kyogre",
    SPECIES_GROUDON: "Groudon",
    SPECIES_RAYQUAZA: "Rayquaza",
    SPECIES_JIRACHI: "Jirachi",
    SPECIES_DEOXYS: "Deoxys",
}

# Name to ID mapping (case-insensitive lookup)
SPECIES_BY_NAME = {name.lower(): species_id for species_id, name in SPECIES_NAMES.items()}


def get_species_name(species_id: int) -> str:
    """Get the name of a Pokemon by its species ID."""
    return SPECIES_NAMES.get(species_id, f"Unknown({species_id})")


def get_species_id(name: str) -> int:
    """Get the species ID by name (case-insensitive)."""
    return SPECIES_BY_NAME.get(name.lower(), SPECIES_NONE)


# =============================================================================
# National Dex Mapping
# =============================================================================
# Gen III uses internal IDs that differ from National Dex numbers for Hoenn Pokemon.
# Gen I & II Pokemon: Internal ID = National Dex Number (1-251)
# Gen III Pokemon: Internal IDs 277-411 map to National Dex 252-386
#
# The offset for Hoenn Pokemon is: Internal ID - 25 = National Dex
# Example: Treecko internal=277, national=252 (277-25=252)

# National Dex to Internal ID mapping (all 386 Pokemon)
NATIONAL_DEX = {
    # Gen I (1-151) - Internal ID = National Dex
    1: SPECIES_BULBASAUR,
    2: SPECIES_IVYSAUR,
    3: SPECIES_VENUSAUR,
    4: SPECIES_CHARMANDER,
    5: SPECIES_CHARMELEON,
    6: SPECIES_CHARIZARD,
    7: SPECIES_SQUIRTLE,
    8: SPECIES_WARTORTLE,
    9: SPECIES_BLASTOISE,
    10: SPECIES_CATERPIE,
    11: SPECIES_METAPOD,
    12: SPECIES_BUTTERFREE,
    13: SPECIES_WEEDLE,
    14: SPECIES_KAKUNA,
    15: SPECIES_BEEDRILL,
    16: SPECIES_PIDGEY,
    17: SPECIES_PIDGEOTTO,
    18: SPECIES_PIDGEOT,
    19: SPECIES_RATTATA,
    20: SPECIES_RATICATE,
    21: SPECIES_SPEAROW,
    22: SPECIES_FEAROW,
    23: SPECIES_EKANS,
    24: SPECIES_ARBOK,
    25: SPECIES_PIKACHU,
    26: SPECIES_RAICHU,
    27: SPECIES_SANDSHREW,
    28: SPECIES_SANDSLASH,
    29: SPECIES_NIDORAN_F,
    30: SPECIES_NIDORINA,
    31: SPECIES_NIDOQUEEN,
    32: SPECIES_NIDORAN_M,
    33: SPECIES_NIDORINO,
    34: SPECIES_NIDOKING,
    35: SPECIES_CLEFAIRY,
    36: SPECIES_CLEFABLE,
    37: SPECIES_VULPIX,
    38: SPECIES_NINETALES,
    39: SPECIES_JIGGLYPUFF,
    40: SPECIES_WIGGLYTUFF,
    41: SPECIES_ZUBAT,
    42: SPECIES_GOLBAT,
    43: SPECIES_ODDISH,
    44: SPECIES_GLOOM,
    45: SPECIES_VILEPLUME,
    46: SPECIES_PARAS,
    47: SPECIES_PARASECT,
    48: SPECIES_VENONAT,
    49: SPECIES_VENOMOTH,
    50: SPECIES_DIGLETT,
    51: SPECIES_DUGTRIO,
    52: SPECIES_MEOWTH,
    53: SPECIES_PERSIAN,
    54: SPECIES_PSYDUCK,
    55: SPECIES_GOLDUCK,
    56: SPECIES_MANKEY,
    57: SPECIES_PRIMEAPE,
    58: SPECIES_GROWLITHE,
    59: SPECIES_ARCANINE,
    60: SPECIES_POLIWAG,
    61: SPECIES_POLIWHIRL,
    62: SPECIES_POLIWRATH,
    63: SPECIES_ABRA,
    64: SPECIES_KADABRA,
    65: SPECIES_ALAKAZAM,
    66: SPECIES_MACHOP,
    67: SPECIES_MACHOKE,
    68: SPECIES_MACHAMP,
    69: SPECIES_BELLSPROUT,
    70: SPECIES_WEEPINBELL,
    71: SPECIES_VICTREEBEL,
    72: SPECIES_TENTACOOL,
    73: SPECIES_TENTACRUEL,
    74: SPECIES_GEODUDE,
    75: SPECIES_GRAVELER,
    76: SPECIES_GOLEM,
    77: SPECIES_PONYTA,
    78: SPECIES_RAPIDASH,
    79: SPECIES_SLOWPOKE,
    80: SPECIES_SLOWBRO,
    81: SPECIES_MAGNEMITE,
    82: SPECIES_MAGNETON,
    83: SPECIES_FARFETCHD,
    84: SPECIES_DODUO,
    85: SPECIES_DODRIO,
    86: SPECIES_SEEL,
    87: SPECIES_DEWGONG,
    88: SPECIES_GRIMER,
    89: SPECIES_MUK,
    90: SPECIES_SHELLDER,
    91: SPECIES_CLOYSTER,
    92: SPECIES_GASTLY,
    93: SPECIES_HAUNTER,
    94: SPECIES_GENGAR,
    95: SPECIES_ONIX,
    96: SPECIES_DROWZEE,
    97: SPECIES_HYPNO,
    98: SPECIES_KRABBY,
    99: SPECIES_KINGLER,
    100: SPECIES_VOLTORB,
    101: SPECIES_ELECTRODE,
    102: SPECIES_EXEGGCUTE,
    103: SPECIES_EXEGGUTOR,
    104: SPECIES_CUBONE,
    105: SPECIES_MAROWAK,
    106: SPECIES_HITMONLEE,
    107: SPECIES_HITMONCHAN,
    108: SPECIES_LICKITUNG,
    109: SPECIES_KOFFING,
    110: SPECIES_WEEZING,
    111: SPECIES_RHYHORN,
    112: SPECIES_RHYDON,
    113: SPECIES_CHANSEY,
    114: SPECIES_TANGELA,
    115: SPECIES_KANGASKHAN,
    116: SPECIES_HORSEA,
    117: SPECIES_SEADRA,
    118: SPECIES_GOLDEEN,
    119: SPECIES_SEAKING,
    120: SPECIES_STARYU,
    121: SPECIES_STARMIE,
    122: SPECIES_MR_MIME,
    123: SPECIES_SCYTHER,
    124: SPECIES_JYNX,
    125: SPECIES_ELECTABUZZ,
    126: SPECIES_MAGMAR,
    127: SPECIES_PINSIR,
    128: SPECIES_TAUROS,
    129: SPECIES_MAGIKARP,
    130: SPECIES_GYARADOS,
    131: SPECIES_LAPRAS,
    132: SPECIES_DITTO,
    133: SPECIES_EEVEE,
    134: SPECIES_VAPOREON,
    135: SPECIES_JOLTEON,
    136: SPECIES_FLAREON,
    137: SPECIES_PORYGON,
    138: SPECIES_OMANYTE,
    139: SPECIES_OMASTAR,
    140: SPECIES_KABUTO,
    141: SPECIES_KABUTOPS,
    142: SPECIES_AERODACTYL,
    143: SPECIES_SNORLAX,
    144: SPECIES_ARTICUNO,
    145: SPECIES_ZAPDOS,
    146: SPECIES_MOLTRES,
    147: SPECIES_DRATINI,
    148: SPECIES_DRAGONAIR,
    149: SPECIES_DRAGONITE,
    150: SPECIES_MEWTWO,
    151: SPECIES_MEW,

    # Gen II (152-251) - Internal ID = National Dex
    152: SPECIES_CHIKORITA,
    153: SPECIES_BAYLEEF,
    154: SPECIES_MEGANIUM,
    155: SPECIES_CYNDAQUIL,
    156: SPECIES_QUILAVA,
    157: SPECIES_TYPHLOSION,
    158: SPECIES_TOTODILE,
    159: SPECIES_CROCONAW,
    160: SPECIES_FERALIGATR,
    161: SPECIES_SENTRET,
    162: SPECIES_FURRET,
    163: SPECIES_HOOTHOOT,
    164: SPECIES_NOCTOWL,
    165: SPECIES_LEDYBA,
    166: SPECIES_LEDIAN,
    167: SPECIES_SPINARAK,
    168: SPECIES_ARIADOS,
    169: SPECIES_CROBAT,
    170: SPECIES_CHINCHOU,
    171: SPECIES_LANTURN,
    172: SPECIES_PICHU,
    173: SPECIES_CLEFFA,
    174: SPECIES_IGGLYBUFF,
    175: SPECIES_TOGEPI,
    176: SPECIES_TOGETIC,
    177: SPECIES_NATU,
    178: SPECIES_XATU,
    179: SPECIES_MAREEP,
    180: SPECIES_FLAAFFY,
    181: SPECIES_AMPHAROS,
    182: SPECIES_BELLOSSOM,
    183: SPECIES_MARILL,
    184: SPECIES_AZUMARILL,
    185: SPECIES_SUDOWOODO,
    186: SPECIES_POLITOED,
    187: SPECIES_HOPPIP,
    188: SPECIES_SKIPLOOM,
    189: SPECIES_JUMPLUFF,
    190: SPECIES_AIPOM,
    191: SPECIES_SUNKERN,
    192: SPECIES_SUNFLORA,
    193: SPECIES_YANMA,
    194: SPECIES_WOOPER,
    195: SPECIES_QUAGSIRE,
    196: SPECIES_ESPEON,
    197: SPECIES_UMBREON,
    198: SPECIES_MURKROW,
    199: SPECIES_SLOWKING,
    200: SPECIES_MISDREAVUS,
    201: SPECIES_UNOWN,
    202: SPECIES_WOBBUFFET,
    203: SPECIES_GIRAFARIG,
    204: SPECIES_PINECO,
    205: SPECIES_FORRETRESS,
    206: SPECIES_DUNSPARCE,
    207: SPECIES_GLIGAR,
    208: SPECIES_STEELIX,
    209: SPECIES_SNUBBULL,
    210: SPECIES_GRANBULL,
    211: SPECIES_QWILFISH,
    212: SPECIES_SCIZOR,
    213: SPECIES_SHUCKLE,
    214: SPECIES_HERACROSS,
    215: SPECIES_SNEASEL,
    216: SPECIES_TEDDIURSA,
    217: SPECIES_URSARING,
    218: SPECIES_SLUGMA,
    219: SPECIES_MAGCARGO,
    220: SPECIES_SWINUB,
    221: SPECIES_PILOSWINE,
    222: SPECIES_CORSOLA,
    223: SPECIES_REMORAID,
    224: SPECIES_OCTILLERY,
    225: SPECIES_DELIBIRD,
    226: SPECIES_MANTINE,
    227: SPECIES_SKARMORY,
    228: SPECIES_HOUNDOUR,
    229: SPECIES_HOUNDOOM,
    230: SPECIES_KINGDRA,
    231: SPECIES_PHANPY,
    232: SPECIES_DONPHAN,
    233: SPECIES_PORYGON2,
    234: SPECIES_STANTLER,
    235: SPECIES_SMEARGLE,
    236: SPECIES_TYROGUE,
    237: SPECIES_HITMONTOP,
    238: SPECIES_SMOOCHUM,
    239: SPECIES_ELEKID,
    240: SPECIES_MAGBY,
    241: SPECIES_MILTANK,
    242: SPECIES_BLISSEY,
    243: SPECIES_RAIKOU,
    244: SPECIES_ENTEI,
    245: SPECIES_SUICUNE,
    246: SPECIES_LARVITAR,
    247: SPECIES_PUPITAR,
    248: SPECIES_TYRANITAR,
    249: SPECIES_LUGIA,
    250: SPECIES_HO_OH,
    251: SPECIES_CELEBI,

    # Gen III (252-386) - Internal IDs 277-411
    # Offset: Internal ID = National Dex + 25
    252: SPECIES_TREECKO,
    253: SPECIES_GROVYLE,
    254: SPECIES_SCEPTILE,
    255: SPECIES_TORCHIC,
    256: SPECIES_COMBUSKEN,
    257: SPECIES_BLAZIKEN,
    258: SPECIES_MUDKIP,
    259: SPECIES_MARSHTOMP,
    260: SPECIES_SWAMPERT,
    261: SPECIES_POOCHYENA,
    262: SPECIES_MIGHTYENA,
    263: SPECIES_ZIGZAGOON,
    264: SPECIES_LINOONE,
    265: SPECIES_WURMPLE,
    266: SPECIES_SILCOON,
    267: SPECIES_BEAUTIFLY,
    268: SPECIES_CASCOON,
    269: SPECIES_DUSTOX,
    270: SPECIES_LOTAD,
    271: SPECIES_LOMBRE,
    272: SPECIES_LUDICOLO,
    273: SPECIES_SEEDOT,
    274: SPECIES_NUZLEAF,
    275: SPECIES_SHIFTRY,
    276: SPECIES_TAILLOW,
    277: SPECIES_SWELLOW,
    278: SPECIES_WINGULL,
    279: SPECIES_PELIPPER,
    280: SPECIES_RALTS,
    281: SPECIES_KIRLIA,
    282: SPECIES_GARDEVOIR,
    283: SPECIES_SURSKIT,
    284: SPECIES_MASQUERAIN,
    285: SPECIES_SHROOMISH,
    286: SPECIES_BRELOOM,
    287: SPECIES_SLAKOTH,
    288: SPECIES_VIGOROTH,
    289: SPECIES_SLAKING,
    290: SPECIES_NINCADA,
    291: SPECIES_NINJASK,
    292: SPECIES_SHEDINJA,
    293: SPECIES_WHISMUR,
    294: SPECIES_LOUDRED,
    295: SPECIES_EXPLOUD,
    296: SPECIES_MAKUHITA,
    297: SPECIES_HARIYAMA,
    298: SPECIES_AZURILL,
    299: SPECIES_NOSEPASS,
    300: SPECIES_SKITTY,
    301: SPECIES_DELCATTY,
    302: SPECIES_SABLEYE,
    303: SPECIES_MAWILE,
    304: SPECIES_ARON,
    305: SPECIES_LAIRON,
    306: SPECIES_AGGRON,
    307: SPECIES_MEDITITE,
    308: SPECIES_MEDICHAM,
    309: SPECIES_ELECTRIKE,
    310: SPECIES_MANECTRIC,
    311: SPECIES_PLUSLE,
    312: SPECIES_MINUN,
    313: SPECIES_VOLBEAT,
    314: SPECIES_ILLUMISE,
    315: SPECIES_ROSELIA,
    316: SPECIES_GULPIN,
    317: SPECIES_SWALOT,
    318: SPECIES_CARVANHA,
    319: SPECIES_SHARPEDO,
    320: SPECIES_WAILMER,
    321: SPECIES_WAILORD,
    322: SPECIES_NUMEL,
    323: SPECIES_CAMERUPT,
    324: SPECIES_TORKOAL,
    325: SPECIES_SPOINK,
    326: SPECIES_GRUMPIG,
    327: SPECIES_SPINDA,
    328: SPECIES_TRAPINCH,
    329: SPECIES_VIBRAVA,
    330: SPECIES_FLYGON,
    331: SPECIES_CACNEA,
    332: SPECIES_CACTURNE,
    333: SPECIES_SWABLU,
    334: SPECIES_ALTARIA,
    335: SPECIES_ZANGOOSE,
    336: SPECIES_SEVIPER,
    337: SPECIES_LUNATONE,
    338: SPECIES_SOLROCK,
    339: SPECIES_BARBOACH,
    340: SPECIES_WHISCASH,
    341: SPECIES_CORPHISH,
    342: SPECIES_CRAWDAUNT,
    343: SPECIES_BALTOY,
    344: SPECIES_CLAYDOL,
    345: SPECIES_LILEEP,
    346: SPECIES_CRADILY,
    347: SPECIES_ANORITH,
    348: SPECIES_ARMALDO,
    349: SPECIES_FEEBAS,
    350: SPECIES_MILOTIC,
    351: SPECIES_CASTFORM,
    352: SPECIES_KECLEON,
    353: SPECIES_SHUPPET,
    354: SPECIES_BANETTE,
    355: SPECIES_DUSKULL,
    356: SPECIES_DUSCLOPS,
    357: SPECIES_TROPIUS,
    358: SPECIES_CHIMECHO,
    359: SPECIES_ABSOL,
    360: SPECIES_WYNAUT,
    361: SPECIES_SNORUNT,
    362: SPECIES_GLALIE,
    363: SPECIES_SPHEAL,
    364: SPECIES_SEALEO,
    365: SPECIES_WALREIN,
    366: SPECIES_CLAMPERL,
    367: SPECIES_HUNTAIL,
    368: SPECIES_GOREBYSS,
    369: SPECIES_RELICANTH,
    370: SPECIES_LUVDISC,
    371: SPECIES_BAGON,
    372: SPECIES_SHELGON,
    373: SPECIES_SALAMENCE,
    374: SPECIES_BELDUM,
    375: SPECIES_METANG,
    376: SPECIES_METAGROSS,
    377: SPECIES_REGIROCK,
    378: SPECIES_REGICE,
    379: SPECIES_REGISTEEL,
    380: SPECIES_LATIAS,
    381: SPECIES_LATIOS,
    382: SPECIES_KYOGRE,
    383: SPECIES_GROUDON,
    384: SPECIES_RAYQUAZA,
    385: SPECIES_JIRACHI,
    386: SPECIES_DEOXYS,
}

# Reverse mapping: Internal ID to National Dex
INTERNAL_TO_NATIONAL = {internal: national for national, internal in NATIONAL_DEX.items()}


def get_national_dex(internal_id: int) -> int:
    """
    Convert internal species ID to National Dex number.

    Args:
        internal_id: The internal species ID used in memory

    Returns:
        National Dex number, or 0 if not found
    """
    return INTERNAL_TO_NATIONAL.get(internal_id, 0)


def get_internal_id(national_dex: int) -> int:
    """
    Convert National Dex number to internal species ID.

    Args:
        national_dex: The National Pokedex number (1-386)

    Returns:
        Internal species ID, or 0 if not found
    """
    return NATIONAL_DEX.get(national_dex, SPECIES_NONE)


def species_from_national_dex(national_dex: int) -> tuple:
    """
    Get species info from National Dex number.

    Args:
        national_dex: The National Pokedex number (1-386)

    Returns:
        Tuple of (internal_id, name) or (0, "Unknown") if not found
    """
    internal_id = NATIONAL_DEX.get(national_dex, SPECIES_NONE)
    if internal_id == SPECIES_NONE:
        return 0, f"Unknown (Dex #{national_dex})"
    name = SPECIES_NAMES.get(internal_id, f"Pokemon #{national_dex}")
    return internal_id, name


# =============================================================================
# Route-specific encounter tables
# =============================================================================

# Route 101 wild encounters
ROUTE_101_SPECIES = {
    SPECIES_POOCHYENA: "Poochyena",
    SPECIES_ZIGZAGOON: "Zigzagoon",
    SPECIES_WURMPLE: "Wurmple",
}

# Route 102 wild encounters
ROUTE_102_SPECIES = {
    SPECIES_POOCHYENA: "Poochyena",
    SPECIES_ZIGZAGOON: "Zigzagoon",
    SPECIES_WURMPLE: "Wurmple",
    SPECIES_LOTAD: "Lotad",
    SPECIES_SEEDOT: "Seedot",
    SPECIES_RALTS: "Ralts",
}

# Starter Pokemon
STARTER_SPECIES = {
    SPECIES_TREECKO: "Treecko",
    SPECIES_TORCHIC: "Torchic",
    SPECIES_MUDKIP: "Mudkip",
}
